config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index' #http get routes/used to retrieve info identified by the url
  get 'welcome/about'
  get 'welcome/contact'
  root to: 'welcome#index' #root is just a hash that takes as an argument

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments #allows a post object to have many comments related to it and provides methods taht enable me to retrieve the comments that belong to a certain post
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def my_name
  @my_name = "Brett Thomas"
end

end

#helpers are available in all views, so the variable created should be truly global

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blobbit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", welcome_index_path %></li> <!-- link_to is a rails helper method: consists of two methods -> "name of hyoerlink", path(generated by routes file) -->
    <li><%= link_to "About", welcome_about_path %></li>
  </ul>

  <%= yield %>  <!-- yield inserts the appropriate view -->
</div>



</body>
</html>


<!-- Understanding the rendering processing

    1. A user requests a view
    2. Controller corresponding TO requested view invokes this page (application.html.erb)
    3. application.html.erb inserts appropriate view using yield
    4. The comeplete webpage is returned to the user

    -->


<!-- Yield method
        -invokes a block in ruby
        -in rails it does the same, but the block its invoking is actually CODE to generate a view

        -->

app/views/welcome/about.html.erb
<h1> About Blobbit:</h2>

  <p> <%= my_name %>, I made this </p>

<p>Find me in app/views/welcome/about.html.erb</p>


<p> <%= my_name %> made this shit </p>

app/views/welcome/contact.html.erb
<p>contact</p>

app/views/welcome/index.html.erb
<h1>Welcome to blobbit</h1>
<p id="index-title">Find me in app/views/welcome/index.html.erb</p>


<div class="posts">Post one goes here.</div>
<div class="posts">Post two goes here.</div>

<section>I am the content in this section.</section>